version: "3.8"

services:
  prometheus:
    build: .
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - coolify-observability
    volumes:
      # - ./prometheus.yml:/etc/prometheus/prometheus.yml
      # - ./rules/:/etc/prometheus/rules/
      # - ./alerts/:/etc/prometheus/alerts/
      - ./data/:/prometheus/
    restart: unless-stopped

networks:
  coolify-observability:
    external: true